CREATE TABLE Users (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(50) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE Pets (
    PetID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    PetName VARCHAR(50) NOT NULL,
    Species VARCHAR(50),
    Breed VARCHAR(50),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
CREATE TABLE PetDetails (
    PetID INT PRIMARY KEY,
    Age INT,
    Weight DECIMAL(5,2), -- e.g., 12.50 kg
    Color VARCHAR(30),
    MedicalHistory TEXT,
    FOREIGN KEY (PetID) REFERENCES Pets(PetID)
);
